name: ping
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
     - name: call pong 
       uses: convictional/trigger-workflow-and-wait@v1.6.1
       with:
         owner: codezninja
         repo: pong
         workflow_file_name: pong.yml
         github_token: ${{ secrets.PAT }}
